# Dockerfile
FROM nginx:latest

# Copy custom Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Copy website content
COPY index.html /usr/share/nginx/html/

# Expose the default Nginx port
EXPOSE 80
