# Use the official MySQL image from Docker Hub
FROM mysql:latest

# Set environment variables for MySQL
# ENV MYSQL_DATABASE=docker_db
# ENV MYSQL_USER=papila
# ENV MYSQL_PASSWORD=papila1011
# ENV MYSQL_ROOT_PASSWORD=papila1011


# Expose the default MySQL port
EXPOSE 3306
