#.github/workflows/terraform
name: Terraform Deployment

on:
  push:
    branches:
      - docker 
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.SESSION_TOKEN }}
  AWS_REGION: "us-east-1"
  backendS3Bucket: "8586-terraform-state"
  backendS3AccountId: ${{ secrets.ACCOUNT_ID }}
  backendS3StateFile: "docker-2.tfstate"
  backendS3region: "us-east-1"
  ECR_REPOSITORY_URI: ${{ secrets.ECR_REPOSITORY_URI }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  IMAGE_TAG: latest



jobs:
  terraform:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
          aws-region: us-east-1


      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init -backend-config="bucket=${{ env.backendS3Bucket }}" -backend-config="key=${{ env.backendS3AccountId }}/${{ env.backendS3StateFile }}" -backend-config="region=${{ env.backendS3Region }}"
          


      - name: Apply Terraform Changes
        run: |
          cd terraform
          terraform plan -var-file=vars.tfvars 
        


      - name: Apply Terraform Changes
        run: |
          cd terraform
          terraform apply -var-file=vars.tfvars -auto-approve


      - name: Destroy Terraform Resources
        if: github.event_name == 'workflow_dispatch'
        run: |
          cd terraform
          terraform destroy -var-file=vars.tfvars -auto-approve


  docker-install:
    needs: [terraform]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Install Docker Dependencies
        run: |
          echo "Running docker.sh script"
          sudo ./docker.sh

      - name: Update APT and Install Docker
        run: |
          echo "Updating APT"
          sudo apt-get update
          echo "Installing Docker and dependencies"
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      

      - name: Verify Docker Installation
        run: |
          echo "Verifying Docker installation"
          docker --version
          docker-compose --version


  build:
    needs: [terraform,docker-install]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
        aws-region: us-east-1
        ECR_REPOSITORY_URI: ${{ env.ECR_REPOSITORY_URI }}
        ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
        IMAGE_TAG: latest

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        region: us-east-1

    - name: Build, tag, and push image to Amazon ECR
      run: |
          docker build -t $ECR_ECR_REPOSITORY_URI/$ECR_REPOSITORY:$IMAGE_TAG .

          docker tag $ECR_ECR_REPOSITORY_URI/$ECR_REPOSITORY:$IMAGE_TAG $ECR_ECR_REPOSITORY_URI/$ECR_REPOSITORY:$IMAGE_TAG

          docker push $ECR_ECR_REPOSITORY_URI/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Verify image pushed to ECR
      run: |
        aws ecr describe-images --repository-name ${{ env.ECR_REPOSITORY }} --region us-east-1


  # configure:
  #   needs: terraform
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4

  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v4


  #     - name: install ansible and dependencies
  #       run: |
  #         pip3 install botocore
  #         pip3 install boto3
  #         pip3 install ansible


  #     - name: run ansible playbook
  #       run: |
  #         cd ansible
  #         ansible-playbook -i aws_ec2.yml playbook.yml   

   


